### ISSUE TITLE
关于rx560

### ISSUE THREAD

**Issue by 1pcr3ss** [juebanlin/P340_Tiny_Opencore_EFI#2]
请问大佬，看配置，p340用前面有缺口的散热器是可以上前代的rx560的吗？
看样子长得和p1000相似，想确认下。

**Comment by juebanlin** [comment]
不记得了，我现在用的是Wx4100，rx560刀卡也就一种吧，而且不好买

**Comment by 1pcr3ss** [comment]
> 不记得了，我现在用的是Wx4100，rx560刀卡也就一种吧，而且不好买

恩，谢谢！
